#+title: Arrays and Strings
#+author: Simon Samuel
#+date: <2025-01-01 Wed>

* Introduction to 2D Array
A two dimensional array is simply a data structure that can be used to store grid like data such as tables or matrices. The underlying structure of the multidimensional array is largely dependent on the language itself. In some languages, the *multidimensional array* is actually implemented internally as a *one-dimensional array*, while in other languages there are no *multidimensional arrays* at all.

C++ stores the array internally as a one-dimensional array while Java stores it as a one-dimensional array of M elements, each of which is an array of N elements.

* Introduction to Strings
A string is just an array of `Unicode Characters`, hence every operation that can be performed on a array can equally be performed on a string but there are some similiarities like the comparison operator can be applied to strings safely on languages like C++ but does not work as expected on Java and JavaScript.

** Immutable Strings
